# -*- coding: utf-8 -*-
"""Copy of detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fEt5zJ6-ZwmqdCyJnAxi_QZPefUOhXD1
"""

from google.colab import drive
drive.mount('/content/drive')

!pip install ultralytics

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/MyDrive/obj-det/yolov5

!python detect.py --weights '/content/drive/MyDrive/obj-det/yolov5/runs/train/yolov5s_results2/weights/best.pt'  --conf 0.4 --iou 0.5 --augment --source '/content/drive/MyDrive/line' --save-txt

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/MyDrive/Milestone- G5/yolov5

!python detect.py \
--weights '/content/drive/MyDrive/obj-det/yolov5/runs/train/yolov5s_results2/weights/best.pt' \
--conf 0.4 \
--iou 0.5 \
--source 0 \
--save-txt