# -*- coding: utf-8 -*-
"""obj-det.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12ylq6FAuRJ8VxhB9m8qU2hTuV1yMm_a4
"""

from google.colab import drive
drive.mount('/content/drive')

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/MyDrive/obj-det

!git clone https://github.com/ultralytics/yolov5

# Commented out IPython magic to ensure Python compatibility.
# %cd yolov5

!pip install -r requirements.txt

!python train.py --batch-size -1 --epochs 100 --data data.yaml --cfg models/yolov5s.yaml --name yolov5s_results  --cache

# Commented out IPython magic to ensure Python compatibility.
# %pwd

!python val.py --batch 60 --data data.yaml --weights 'runs/train/yolov5s_results2/weights/best.pt' --task val --name 'yolov5s Validation' --augment --save-txt

!python export.py --weights 'runs/train/yolov5s_results2/weights/best.pt' --include tflite --img 416

